autoSwitchAppearance: true
enableSearch: true
enableCodeCopy: true
smartTOC: true
robots: all
dateFormat: 2006-01-02

# https://blowfish.page/docs/getting-started/#colour-schemes
colorScheme: github

homepage:
  layout: profile
  showRecent: true

footer:
  showAppearanceSwitcher: true

article:
  showTableOfContents: true
  showEdit: true
  editURL: https://github.com/NelsonDane/blog/tree/main/content/
  showWordCount: false
  showAuthorBottom: true
  showTaxonomies: true
  showRelatedContent: true
  relatedContentLimit: 3
  showHero: true
  showComments: true
  heroStyle: background
  showViews: true
  showLikes: true

list:
  showHero: true
  showSummary: false

firebase:
  apiKey: AIzaSyBo7BXRtB4zjc9LyYb0c78bJKKqxOyaxgQ
  authDomain: blog-58d83.firebaseapp.com
  projectId: blog-58d83
  storageBucket: blog-58d83.appspot.com
  messagingSenderId: 43679632557
  appId: 1:43679632557:web:2f701b9102a35ebf124a24
  measurementId: G-1BPQ8JLBXM
